apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mollysocket-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: placeholder
  resources:
    requests:
      storage: 1Gi
