name: Test

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt update -y && sudo apt install -y libsqlite3-dev
    - name: Run tests
      run: cargo test --verbose
